
import {
  ClerkProvider,
  
  
} from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import type { Metadata } from 'next'
import './globals.css'
import {Inter} from 'next/font/google'
import { cn } from '@/lib/utils'
const inter = Inter ({subsets: ['latin']})
export const metadata: Metadata={
  title:'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="fr">
        <body className={cn(inter.className,"bg-white, dark:bg-[#313338]")}>
       
          <ThemeProvider
            attribute="class"
            defaultTheme="white"
            enableSystem
            storageKey= "discord-theme"
          >
            {children}
          </ThemeProvider>
          
          
        </body>
      </html>
    </ClerkProvider>
  )
}
